services:

  db:
    image: docker.io/mariadb
    restart: always
    env_file:
      - .env
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - squadjs-mariadb:/var/lib/mysql

  squadjs:
    image: ghcr.io/comunidad-hispana-squad/squadjs-docker:latest
    volumes:
      - squadjs-sqlite:/app/database.sqlite
      - ./squadjs-config.json:/app/config.json
      - ./Admins.cfg:/app/Admins.cfg
      - ./squad-data/SquadGame/ServerConfig/:/app/ServerConfig
      - ./plugins:/app/squad-server/plugins

volumes:
  squadjs-sqlite:
  squadjs-mariadb: